### ISSUE TITLE
Class names are outdated so the scraper doesn't work

### ISSUE THREAD

**Issue by mileyvirus** [buckket/ofgrab#1]
Hey buckket! 👋

Is the script still working for you? I tried using it for the first time and it throws
`[!] No posts found, there seems to be a problem` on me. I tried with getting new `sess` ids but it always gives me that error.

**Comment by buckket** [comment]
Maybe they’ve changed their HTML code in a way that the script’s parser doesn’t recognize it anymore. Currently I don’t have access to private profiles on OF so there’s no easy way for me to check or work around it.

Maybe you, or somebody else, could provide the HTML source of a profile?

**Comment by astultgyidftud545** [comment]
> Maybe you, or somebody else, could provide the HTML source of a profile?

Hi. I emailed you one, hopefully it helps. thanks

**Comment by buckket** [comment]
@astultgyidftud545 Haven’t received anything so far :/

#2 seems to fix the problem. Will verify and merge soon.

**Comment by mileyvirus** [comment]
> @astultgyidftud545 Haven’t received anything so far :/
> 
> #2 seems to fix the problem. Will verify and merge soon.

Unfortunately it oddly still gives `[!] No posts found, there seems to be a problem`.

**Comment by mileyvirus** [comment]
> Maybe they’ve changed their HTML code in a way that the script’s parser doesn’t recognize it anymore. Currently I don’t have access to private profiles on OF so there’s no easy way for me to check or work around it.

They did change some HTML but that's not it, printing r.text shows that login via the sess cookie does not work anymore so authentication is the main problem! I tried using [pycookiecheat](https://github.com/n8henrie/pycookiecheat) and using my full Chrome cookie but still can't get authenticated.

> Maybe you, or somebody else, could provide the HTML source of a profile?

Unfortunately my only sub expired yesterday aha… ☹

**Comment by astultgyidftud545** [comment]
I don't suppose there is a fix for this?
Would be greatly appreciated

**Comment by mileyvirus** [comment]
@buckket I sent you an email titled **HTML page of an OnlyFans subscriber**. It has the code of a real live page of a profile I subbed to!

**Comment by buckket** [comment]
I’ve updated the code to work with the new HTML class names. However I haven’t been able to test if scraping multiple pages still works correctly.

**Heads up**: Apparently OF now also compares the User-Agent string and not only the `sess` cookie. So for authentication to work you not only have to copy the cookie but also the exact User-Agent string of the browser you were using to log in into OF.

```
./ofgrab.py '<PROFILE_NAME>' '<YOUR_SESSION_ID>' '<USER_AGENT_STRING>'
```

If someone could verify that everything works, that would be great.

**Comment by mileyvirus** [comment]
Great job @buckket authentication now works passing the User Agent String.
Unfortunately it only scrapes the first page tho. This is the output for an OF user with 80 posts, 30 pics, 50 vids.

```
Computer:ofgrab-master user$ ./ofgrab.py *profile* *sess* "*useragent*"
[!] Found 10 posts on the start page
- Added video from post *postID*
- Added video from post *postID*
- Added video from post *postID*
- Added video from post *postID*
- Added video from post *postID*
- Added video from post *postID*
- Added image from post *postID*
- Added video from post *postID*
- Added video from post *postID*
- Added image from post *postID*
[!] Fetching additional page
[!] Fetching additional page
[!] Fetching additional page
[!] Fetching additional page
[!] Fetching additional page
[!] Fetching additional page
[!] Fetching additional page
[!] Nothing more to process
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/images/mediaID.jpeg
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/videos/mediaID.mp4
- Downloading *profile*/images/mediaID.jpeg
```

**Comment by buckket** [comment]
@mileyvirus At least fetching more pages seems to work, but we were unable to detect the post data in it. Makes sense because I forgot to update the new class names there. Fingers crossed; it should work now. Maybe you could give it another try?

**Comment by mileyvirus** [comment]
Top notch work @buckket now every page gets scraped!

There's still an issue: pictures in carousels don't get scraped, I'll open a new issue and close this one so you can consider if you wanna work on it or not.

Thank you very much for fixing!

**Comment by davdavis9** [comment]
sorry can someone pm me help. Im still getting the "No posts found" error
